/** @format */

export const extensionIconPaths: Record<string, string> = {
	// File

	tsx: "/public/icons/file/reactts",
	jsx: "/public/icons/file/reactjs",
	js: "/public/icons/file/js",
	ts: "/public/icons/file/ts",
	html: "/public/icons/file/html",
	css: "/public/icons/file/css",
	cpp: "/public/icons/file/cpp",
	c: "/public/icons/file/c",
	csharp: "/public/icons/file/csharp",
	dart: "/public/icons/file/dart",
	db: "/public/icons/file/db",
	git: "/public/icons/file/git",
	json: "/public/icons/file/json",
	php: "/public/icons/file/php",
	py: "/public/icons/file/python",
	gradle: "/public/icons/file/gradle",
	graphql: "/public/icons/file/graphql",
	rest: "/public/icons/file/rest",
	scss: "/public/icons/file/scss",
	sql: "/public/icons/file/sql",
	svg: "/public/icons/file/svg",
	swift: "/public/icons/file/swift",
	vue: "/public/icons/file/vue",

	// Folder

	node_modules: "/public/icons/folder/nginx",
	public: "/public/icons/folder/public",
	src: "/public/icons/folder/src",
	android: "/public/icons/folder/android",
	api: "/public/icons/folder/api",
	app: "/public/icons/folder/app",
	bloc: "/public/icons/folder/bloc",
	config: "/public/icons/folder/config",
	docker: "/public/icons/folder/docker",
	github: "/public/icons/folder/github",
	hook: "/public/icons/folder/hook",
	images: "/public/icons/folder/images",
	ios: "/public/icons/folder/ios",
	Json: "/public/icons/folder/json",
	mongodb: "/public/icons/folder/mongodb",
	mysql: "/public/icons/folder/mysql",
	node: "/public/icons/folder/node",
	nuxt: "/public/icons/folder/nuxt",
	redux: "/public/icons/folder/redux",
	route: "/public/icons/folder/route",
	services: "/public/icons/folder/services",
	style: "/public/icons/folder/style",
	temp: "/public/icons/folder/temp",
	tools: "/public/icons/folder/tools",
};
